name: generate_pdoc
on:
  push:
    branches:
      - main
    paths:
      - "*.py"
  pull_request:
    branches:
      - main
    paths:
      - "*.py"
  workflow_dispatch:

jobs:
  generate_pdoc:
    name: generating pdoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # set up python
      - name: Setting up python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        
      # install pdoc
      - name: Install Pdoc
        run: pip install pdoc
          

      # pdoc run 
      - name: Pdoc
        run: pdoc -o ./html pdoc
      
      # deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
